Repository Famailyship-org/recSys.checkkuleogo.org, pull requests merged in 2024-10, with the labels that each got.

#2 [feature/recSys-1] 프로젝트 구조 설계
  app/config.py
  app/db/database.py
  app/models/schemas.py
  app/routers/hybrid_rec_sys.py
  app/schedulers/tasks.py
  app/services/cf_rec_sys_service.py
  app/services/cs_rec_sys_service.py
  app/services/hybrid_rec_sys_service.py
Labels: enhancement, good first issue

#7 [Feature/rec sys 4] CS 기본 구현
  .DS_Store
  .gitignore
  Dockerfile
  app/config/database.py
  app/config/secrets.json
  app/main.py
  app/models/schemas.py
  app/schedulers/scheduler.py
  app/schedulers/tasks.py
  app/services/cs_rec_sys_service.py
  app/sqlTest/book_data.sql
  requirements.txt
Labels: enhancement

#10 [feature/recSys-3] CF 기본 구현
  .gitignore
  app/main.py
  app/models/schemas.py
  app/schedulers/scheduler.py
  app/services/cf_rec_sys_service.py
  app/sqlTest/like_test.py
  requirements.txt
Labels: enhancement

#15 [feature/recSys-5] CS 추천 시스템, 배치 및 피벗 테이블 적용 -> 80프로 이상 성능개선
  app/config/secrets.json
  app/schedulers/scheduler.py
  app/services/cs_rec_sys_service.py
  app/sqlTest/book_data.sql
Labels: enhancement

#19 [feature/recSys-8] 점수 반환 및 하이브리드 가중치 추가
  app/services/cf_rec_sys_service.py
  app/services/cs_rec_sys_service.py
  app/services/hybrid_rec_sys_service.py
Labels: enhancement

#21 [feature/recSys-9] 동적 가중치 추가
  app/services/hybrid_rec_sys_service.py
Labels: enhancement

#23 [feature/recSys-10] 휴면 유저 추천 시스템 제외 처리
  app/services/cf_rec_sys_service.py
  app/services/cs_rec_sys_service.py
  app/services/hybrid_rec_sys_service.py
Labels: enhancement, help wanted, question
